// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTngaLiUOgCIg17T2V7NowVCcD9-vLhwg',
    appId: '1:542178760959:web:ebd9b0a92b6875476414ca',
    messagingSenderId: '542178760959',
    projectId: 'messaging-app-97895',
    authDomain: 'messaging-app-97895.firebaseapp.com',
    storageBucket: 'messaging-app-97895.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6aVTS7Y3gCJPOy9fGvGnTNh95dvLiwxc',
    appId: '1:542178760959:android:274315cb5fb5c9df6414ca',
    messagingSenderId: '542178760959',
    projectId: 'messaging-app-97895',
    storageBucket: 'messaging-app-97895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqumEJxv0RufSt8RMNtRen8ySB7Bkzj0',
    appId: '1:542178760959:ios:e892e4235e5f7e9e6414ca',
    messagingSenderId: '542178760959',
    projectId: 'messaging-app-97895',
    storageBucket: 'messaging-app-97895.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqumEJxv0RufSt8RMNtRen8ySB7Bkzj0',
    appId: '1:542178760959:ios:e892e4235e5f7e9e6414ca',
    messagingSenderId: '542178760959',
    projectId: 'messaging-app-97895',
    storageBucket: 'messaging-app-97895.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTngaLiUOgCIg17T2V7NowVCcD9-vLhwg',
    appId: '1:542178760959:web:ed230906c0d6ad606414ca',
    messagingSenderId: '542178760959',
    projectId: 'messaging-app-97895',
    authDomain: 'messaging-app-97895.firebaseapp.com',
    storageBucket: 'messaging-app-97895.appspot.com',
  );

}